spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: template-pool
      maximum-pool-size: 10
      minimum-idle: 1
    type: com.zaxxer.hikari.HikariDataSource
